apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: wls-admin-server
spec:
  serviceName: wls-admin-server
  replicas: 1
  template:
    metadata:
      labels:
        app: wls-admin-server
    spec:
      containers:
      - name: wls-admin-server
        image: wls-12213-oow-demo-domain
        imagePullPolicy: Never
        command: ["sh"]
        args: ["/u01/oracle/startadmin.sh"]
        readinessProbe:
            httpGet:
              path: /weblogic/ready
              port: 8001
            initialDelaySeconds: 15
            timeoutSeconds: 5
        ports:
        - containerPort: 8001
        env:
        - name: JAVA_OPTIONS
          value: "-Dweblogic.StdoutDebugEnabled=false"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DNS_DOMAIN_NAME
          value: "wls-subdomain"


---
apiVersion: v1 # headless service required for statefulSet
kind: Service
metadata:
  name: wls-admin-server
  labels:
    app: wls-admin-server
spec:
  ports:
  - name: client
    port: 8001
    protocol: TCP
    targetPort: 8001
  clusterIP: None
  selector:
    app: wls-admin-server

---

apiVersion: v1
kind: Service
metadata:
  name: wls-admin-service
spec:
  type: NodePort
  selector:
    app: wls-admin-server
  ports:
    - name: client
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001
  selector:
    app: wls-admin-server

