apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: ms
spec:
  serviceName: wls-subdomain
  replicas: 2
  template:
    metadata:
      name: ms
      labels:
        app: wls-k8s-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/wls-exporter/metrics"
    spec:
      subdomain: wls-subdomain
      containers:
      - name: ms
        image: karankapoor/wls-12213-oow-demo-domain:latest
        imagePullPolicy: Never
        command: ["sh"]
        args: ["/u01/oracle/startms.sh"]
        readinessProbe:
            httpGet:
              path: /weblogic/ready
              port: 8011
            initialDelaySeconds: 15
            timeoutSeconds: 5
        ports:
        - containerPort: 8011
        env:
        - name: JAVA_OPTIONS
          value: "-Dweblogic.StdoutDebugEnabled=false"
        - name: USER_MEM_ARGS
          value: "-Xms64m -Xmx256m -XX:NewRatio=3"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DNS_DOMAIN_NAME
          value: "wls-subdomain"


---

apiVersion: v1 # headless service required for statefulSet
kind: Service
metadata:
  name: wls-subdomain
  labels:
    app: wls-k8s-demo
spec:
  ports:
  - name: client
    port: 8011
    protocol: TCP
    targetPort: 8011
  clusterIP: None
  selector:
    app: wls-k8s-demo

---

apiVersion: v1
kind: Service
metadata:
  name: wls-service
  labels:
    app: wls-k8s-demo
spec:
  type: NodePort
  ports:
  - name: client
    port: 8011
    protocol: TCP
    targetPort: 8011
    nodePort: 30011
  selector:
    app: wls-k8s-demo


