slave0:
  container_name: "slave0"
  hostname: "slave0"
  build: "slave/"
  net: "nosql"
slave1:
  container_name: "slave1"
  hostname: "slave1"
  build: "slave/"
  net: "nosql"
master:
  container_name: "master"
  hostname: "master"
  build: "master/"
  net: "nosql"
  ports:
   - 5001
