# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# Example of using Docker Compose to deploy a WebLogic Cluster from image '1221-domain'
#
# This Docker Compose file will only work with Docker 1.10+ and Compose 1.6+
#
# To run, call:
#   $ docker-compose up
#
# To scale Managed Servers, open a new terminal and call:
#   $ docker-compose scale managedserver=2
#
# To scale Node Managers only instead, call:
#   $ docker-compose scale nodemanager=2
#
# Author: Bruno Borges <bruno.borges@oracle.com>
#
# Note: If scaling dozens of instances of managed server at once, you may face a StuckThreadMaxTime
#
# Important: Restarting services will not work as expected due to hostnames not being properly setup by Docker Compose.
#            WLS still relying on IP addresses because of that.
#            See https://github.com/docker/compose/issues/2551#issuecomment-183082781
#            Issue is fixed on upstream only (1.7+), not 1.6.0
#            See https://github.com/docker/compose/pull/2853
#
version: '2'

networks:
  &network wlsnet:
    driver: bridge

services:

  # Deploys the AdminServer with default hostname 'wlsadmin' used by scripts in 1221-domain.
  &admin adminserver:
    image: &image 1221-appdeploy
    container_name: wlsadmin
    networks:
      - *network

  # Deploys a container running a Managed Server and a Node Manager to control MS from AdminServer
  managedserver:
    image: *image
    command: createServer.sh
    networks:
      - *network
    depends_on:
      - *admin

  # Deploys a container running only a node manager. to deploy a managed server here later, use AdminServer Web Console
  nodemanager:
    image: *image
    command: createMachine.sh
    networks:
      - *network
    depends_on:
      - *admin

  # WebTier for load balancing requests to cluster
  webtier:
    image: 1221-webtier-apache
    networks:
      - *network
    environment:
      - WEBLOGIC_CLUSTER="managedserver:7002"
    links:
      - managedserver
