#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

# Default values for oracle-db. Please check README for more information about below parameters

##This parameter changes the ORACLE_SID of the database. The default value is set to ORCLCDB.
oracle_sid: ORCLCDB

##This parameter modifies the name of the PDB. The default value is set to ORCLPDB1.
oracle_pdb: ORCLPDB1

## The Oracle Database SYS, SYSTEM and PDB_ADMIN password. Defaults to a randomly generated password
oracle_pwd:

## The character set to use when creating the database. Defaults to AL32UTF8
oracle_characterset: AL32UTF8

## The database edition (default: enterprise)
oracle_edition: enterprise

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
persistence:
  ## Oracle database data Persistent Volume Storage Class, nfs or block
  storageClass: ""
  size: 100Gi

## Deploy only on nodes in a particular availability domain, eg PHX-AD-1 on OCI
## Leave empty if there is no such requirement
availabilityDomain:

## Deploy multiple replicas for fast fail over
replicas: 1

## deploy LoadBalancer service
loadBalService: false

## name of image
image: container-registry.oracle.com/database/enterprise:19.3.0.0

## image pull policy, IfNotPresent or Always
imagePullPolicy: Always

## container registry login/password
imagePullSecrets:

## Deploy only on nodes in a particular nodepool having label "pool"
## Leave empty if there is no such requirement
pool:

