apiVersion: v1
kind: Service
metadata:
  name: tuxedo-loadbal-svc
spec:
  type: LoadBalancer
  selector:
    app: tuxedows-svr
  ports:
    - name: wsl
      port: 9055
      targetPort: 9055
    - name: ssl
      port: 9060
      targetPort: 9060
    - name: wsh1
      port: 2071
      targetPort: 2071
    - name: wsh2
      port: 2072
      targetPort: 2072
    - name: wsh3
      port: 2073
      targetPort: 2073
    - name: wsh4
      port: 2074
      targetPort: 2074
    - name: wsh5
      port: 2075
      targetPort: 2075
