name: Build and publish NoSQL secure container image to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'NoSQL/ce-sec/*'
      - '.github/workflows/build-and-push-nosql-sec-image.yml'
  workflow_dispatch:

env:
  IMAGE_NAME: nosql

jobs:
  push:
    name: Build and push NoSQL ce image

    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Repository owner needs to be lowercase
        id: repo-owner
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          echo "repo-owner=${REPO_OWNER,,}" >> "$GITHUB_OUTPUT"
      - 
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Generate container image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ steps.repo-owner.outputs.repo-owner }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
                type=raw,value=latest-ce-sec
                type=raw,value=${{ env.TAG }}
        env:
          TAG: ${{ steps.date.outputs.date }}-ce-sec
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./NoSQL/ce-sec/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
 
